#! /usr/bin/perl

print STDERR "Git-MediaWiki is no longer maintained at https://github.com/Bibzball/Git-Mediawiki/\";
print STDERR "Instead, it is now in the contrib/mw-to-git/ directory of Git itself.\n";
print STDERR "See for example https://github.com/git/git/tree/pu/contrib/mw-to-git\n";
print STDERR "Only the wiki is still at https://github.com/Bibzball/Git-Mediawiki/wiki\n";